site_name: Fed-BioMed
site_url: https://fedbiomed.org/latest
site_dir: public

site_description: >-
    Open, Transparent and Trusted Collaborative Learning for Real-world Healthcare Applications
theme:
  name: material
  logo: assets/img/fedbiomed-logo-small.png
  custom_dir: docs/.templates/theme/
  language: en


nav:
  - Top-Bar:
      - 'Home': './index.md'
      - 'User Documentation': './getting-started/what-is-fedbiomed.md'
      - 'About': './pages/about-us.md'
      - 'More' :
        - 'Funding' : './#funding'
        - 'News' : './news/index.md'
        - 'Contributors': './#contributors'
        - 'Users': './#users'
        - 'Roadmap': './pages/roadmap.md'
        - 'How to Cite Us' : './#citation'
        - 'Contact Us' : './#contact-us'
  - Docs:
    - 'Getting Started':
      - "What's Fed-BioMed": './getting-started/what-is-fedbiomed.md'
      - 'Fedbiomed Architecture': './getting-started/fedbiomed-architecture.md'
      - 'Fedbiomed Workflow': './getting-started/fedbiomed-workflow.md'
      - 'Installation': './getting-started/installation.md'
      - 'Basic Example': './getting-started/basic-example.md'
      - 'Configuration': './getting-started/configuration.md'
    - Tutorials:
      - PyTorch:
        - 'MNIST Basic Example': './tutorials/pytorch/01_PyTorch_MNIST_Single_Node_Tutorial.ipynb'
        - 'Create Your Custom Training Plan': './tutorials/pytorch/02_Create_Your_Custom_Training_Plan.ipynb'
        - 'Regression Example with Used Cars Dataset': './tutorials/pytorch/03_PyTorch_Used_Cars_Dataset_Example.ipynb'
        - 'Aggregators in Fed-BioMed': './tutorials/pytorch/04-Aggregation_in_Fed-BioMed.ipynb'
        - 'Transfer-Learning in Fed-BioMed': './tutorials/pytorch/05_Transfer-learning_tutorial_usingDenseNet-121.ipynb'
      - MONAI:
        - '2D Image Classification with MedNIST': './tutorials/monai/01_monai-2d-image-classification.ipynb'
        - '2D Image Registration with MedNIST': './tutorials/monai/02_monai-2d-image-registration.ipynb'
      - Scikit-Learn:
        - 'MNIST Basic Example': "./tutorials/scikit-learn/01_sklearn_MNIST_classification_tutorial.ipynb"
        - 'Regression with Scikit-Learn':  './tutorials/scikit-learn/02_sklearn_sgd_regressor_tutorial.ipynb'
        - 'More Scikit-Learn models': './tutorials/scikit-learn/03-other-scikit-learn-models.ipynb'
      - Optimizers:
        - 'Advanced Optimizers': './tutorials/optimizers/01-fedopt-and-scaffold.ipynb'
      - FLamby:
        - 'General Concepts': "./tutorials/flamby/flamby.md"
        - 'FLamby examples': "./tutorials/flamby/flamby-integration-into-fedbiomed.ipynb"
      - Advanced:
        - 'In Depth Experiment Configuration': './tutorials/advanced/in-depth-experiment-configuration.ipynb'
        - 'Training with GPU' : './tutorials/advanced/training-with-gpu.ipynb'
        - 'Breakpoints' : './tutorials/advanced/breakpoints.md'
      - Security:
          - 'Differential Privacy (DP) with OPACUS': './tutorials/security/differential-privacy-with-opacus-on-fedbiomed.ipynb'
          - 'Local and Central DP Example': './tutorials/security/non-private-local-central-dp-monai-2d-image-registration.ipynb'
          - 'Training with Approved Model Files' : './tutorials/security/training-with-approved-training-plans.ipynb'
          - 'Secure Aggregation': './tutorials/security/secure-aggregation.ipynb'
          - 'End-to-end Privacy Preserving Training and Inference on Medical Data': './tutorials/concrete-ml/concrete-ml.ipynb'
      - Biomedical data:
          - 'Brain image segmentation using IXI dataset': './tutorials/medical/medical-image-segmentation-unet-library.ipynb'
    - 'User Guide':
      - Glossary: './user-guide/glossary.md'
      - Deployment:
          - "Introduction": './user-guide/deployment/deployment.md'
          - "Fed-BioMed Docker Containers": './user-guide/deployment/docker.md'
          - "VPN Deployment": './user-guide/deployment/deployment-vpn.md'
          - "Network matrix": './user-guide/deployment/matrix.md'
          - "Security model": './user-guide/deployment/security-model.md'
      - Node:
        - "Configuring Nodes": './user-guide/nodes/configuring-nodes.md'
        - "Deploying Datasets" : './user-guide/nodes/deploying-datasets.md'
        - "Training Plan Management" : './user-guide/nodes/training-plan-security-manager.md'
        - "Using GPU" : './user-guide/nodes/using-gpu.md'
        - "Node GUI" : './user-guide/nodes/node-gui.md'
      - Researcher:
        - "Training Plan": './user-guide/researcher/training-plan.md'
        - "Training Data": './user-guide/researcher/training-data.md'
        - "Experiment": './user-guide/researcher/experiment.md'
        - "Aggregation": './user-guide/researcher/aggregation.md'
        - "Listing Datasets and Selecting Nodes" : './user-guide/researcher/listing-datasets-and-selecting-nodes.md'
        - "Model Validation on the Node Side": './user-guide/researcher/model-testing-during-federated-training.md'
        - "Tensorboard" : './user-guide/researcher/tensorboard.md'
      - Optimization: './user-guide/advanced-optimization.md'
      - "Secure Aggregation":
          - "Introduction": './user-guide/secagg/introduction.md'
          - "Configuration": './user-guide/secagg/configuration.md'
          - "Managing Secure Aggregation in Researcher": './user-guide/secagg/researcher-interface.md'
    - Developer:
        - 'API Reference':
            - Common:
                - 'Certificate Manager': './developer/api/common/certificate_manager.md'
                - CLI: './developer/api/common/cli.md'
                - Config: './developer/api/common/config.md'
                - Constants: './developer/api/common/constants.md'
                - Data: './developer/api/common/data.md'
                - DB: './developer/api/common/db.md'
                - Exceptions: './developer/api/common/exceptions.md'
                - IPython: './developer/api/common/ipython.md'
                - Json: './developer/api/common/json.md'
                - Logger: './developer/api/common/logger.md'
                - Message: './developer/api/common/message.md'
                - Metrics: './developer/api/common/metrics.md'
                - Model: './developer/api/common/models.md'
                - 'MPC controller': './developer/api/common/mpc_controller.md'
                - Optimizers: './developer/api/common/optimizers.md'
                - Privacy: './developer/api/common/privacy.md'
                - Secagg: './developer/api/common/secagg.md'
                - 'Secagg Manager': './developer/api/common/secagg_manager.md'
                - Serializer: './developer/api/common/serializer.md'
                - Singleton: './developer/api/common/singleton.md'
                - Synchro: './developer/api/common/synchro.md'
                - TasksQueue: './developer/api/common/tasks_queue.md'
                - TrainingPlans: './developer/api/common/training_plans.md'
                - TrainingArgs: './developer/api/common/training_args.md'
                - Utils: './developer/api/common/utils.md'
                - Validator: './developer/api/common/validator.md'
            - Node:
                - CLI: './developer/api/node/cli.md'
                - 'CLI Utils': './developer/api/node/cli_utils.md'
                - Config: './developer/api/node/config.md'
                - DatasetManager: './developer/api/node/dataset_manager.md'
                - HistoryMonitor: './developer/api/node/history_monitor.md'
                - Node: './developer/api/node/node.md'
                - NodeStateManager: './developer/api/node/node_state_manager.md'
                - Requests: './developer/api/node/requests.md'
                - Round: './developer/api/node/round.md'
                - Secagg: './developer/api/node/secagg.md'
                - 'Secagg Manager': './developer/api/node/secagg_manager.md'
                - TrainingPlanSecurityManager: './developer/api/node/training_plan_security_manager.md'
            - Researcher:
                - Aggregators: './developer/api/researcher/aggregators.md'
                - CLI: './developer/api/researcher/cli.md'
                - Config: './developer/api/researcher/config.md'
                - Datasets: './developer/api/researcher/datasets.md'
                - Federated Workflows: './developer/api/researcher/federated_workflows.md'
                - Filetools: './developer/api/researcher/filetools.md'
                - Jobs: './developer/api/researcher/jobs.md'
                - Monitor: './developer/api/researcher/monitor.md'
                - NodeStateAgent: './developer/api/researcher/node_state_agent.md'
                - Requests: './developer/api/researcher/requests.md'
                - Secagg: './developer/api/researcher/secagg.md'
                - Strategies: './developer/api/researcher/strategies.md'
            - Transport:
                - Client: './developer/api/transport/client.md'
                - Controller: './developer/api/transport/controller.md'
                - NodeAgent: './developer/api/transport/node_agent.md'
                - Server: './developer/api/transport/server.md'
        - 'Building Docker Images': './developer/docker-images.md'
        - 'Usage and Tools': './developer/usage_and_tools.md'
        - 'Continuous Integration': './developer/ci.md'
        - 'Definition of Done': './developer/definition-of-done.md'
        - 'Development Environment': './developer/development-environment.md'
        - 'Testing in Fed-BioMed': './developer/testing-in-fedbiomed.md'
        - 'RPC Protocol and Messages': './developer/messaging.md'
  #    - 'API Reference': ./developer/api/ # Uncomment this if auto generate is active
    - 'FAQ & Troubleshooting': './support/troubleshooting.md'
  - Footer:
    - 'News' : './news/index.md'
    - 'Contributors': './pages/contributors.md'
    - 'Contact Us' : './pages/contact-us.md'

extra:
  NewsPosts:
      'Release-02-2025':
          name: 'A new release of Fed-BioMed (v6.0) is now available!'
          desc: 'A new major version of Fed-BioMed is now available, featuring a new API and more!'
          link: '/news/Release-02-2025'
          image: '/assets/Release-02-2025.png'
      'Release-11-2024':
          name: 'A new release of Fed-BioMed (v5.4) is out!'
          desc: 'A new release of Fed-BioMed is now available, improving secure aggregation !'
          link: '/news/Release-11-2024'
          image: 'assets/img/v5.4.png'
      'Release-9-2024':
          name: 'A new release of Fed-BioMed (v5.3) is out!'
          desc: 'A new release of Fed-BioMed is now available, introducing LOM secure aggregation !'
          link: '/news/Release-09-2024'
          image: 'assets/img/v5.3.png'
      'Release-5-2024':
          name: 'A new release of Fed-BioMed (v5.2) is out!'
          desc: 'A new release of Fed-BioMed is now available, fixing known issues and introducing new end-to-end test facility'
          link: '/news/Release-05-2024'
          image: 'assets/img/v5.2.jpg'
      'WAICF-2024':
          name: 'Fed-BioMed @ WAICF 2024'
          desc: 'Fed-BioMed at WAICF 2024 on February 8-9'
          link: '/news/waicf-2024'
          image: 'assets/img/waicf2024.png'
      'Release-12-2023':
          name: 'A new release of Fed-BioMed (v5.0) is out!'
          desc: 'A new release of Fed-BioMed is now available, introducing gRPC communication layer !'
          link: '/news/Release-12-2023'
          image: 'assets/img/v5.0.png'
      'VivaTech-2023':
          name: 'Fed-BioMed @ Viva Technology 2023'
          desc: 'Fed-BioMed at Viva Technology 2023 on June 16'
          link: '/news/vivatech-2023'
          image: 'assets/img/vivatech2023.png'
      'Release-04-2023':
          name: 'A new release of Fed-BioMed (v4.3) is out!'
          desc: 'A new release of Fed-BioMed is now available, introducing Secure Aggregation !'
          link: '/news/Release-04-2023'
          image: 'assets/img/v4.3.jpg'
      'Release-01-05':
          name: 'A new release of Fed-BioMed (v4.1) is out!'
          desc: 'A new release of Fed-BioMed (v4.1) is out, introducing Scaffold aggregator, more integration tests'
          link: '/news/Release-01-2023'
          image: 'assets/img/v4.1.jpg'
      'federated-pet':
          name: 'Fed-BioMed for Federated-PET project'
          desc: 'Federated-PET groups 8 hospitals and 4 research centers in an oncology research project.'
          link: '/news/federated-pet'
          image: 'assets/img/VF-logo-FP-partenaires.jpg'
      'OSE-2022':
          name: 'Fed-BioMed @ Open Source Experience 2022'
          desc: 'Fed-BioMed participated to Open Source Experience 2022 meeting of the European open source community, Paris, Nov 8-9.'
          link: '/news/OSE-2022'
          image: 'assets/img/ose2022.jpg'
      'Release-11-2022':
          name: 'A new major release of Fed-BioMed (v4.0)!'
          desc: 'A new release of Fed-BioMed is now available: Differential privacy, Training Plan approval, support for multi-modality imaging data, and much more !'
          link: '/news/Release-11-2022'
          image: 'assets/img/v4.0.jpg'
      'Release-05-2022':
          name: 'A new release of Fed-BioMed (v3.5)!'
          desc: 'A new release of Fed-BioMed is now available: model validation, FedProx, NIFTI and MedNIST datasets and much more !'
          link: '/news/Release-05-2022'
          image: '/assets/img/v3.5.jpg'
      'CAL_oncology':
          name: 'Fed-BioMed for oncology research'
          desc: 'Fed-BioMed contributes to oncology research projects from Centre Antoine Lacassagne.'
          link: '/news/CAL_oncology'
          image: 'assets/img/CAL.png'
      'Release-02-2022':
          name: 'A new release of Fed-BioMed (v3.4)!'
          desc: 'A new release of Fed-BioMed is now available: DP with Opacus, GUI for node data, GPU for PyTorch and much more !'
          link: '/news/Release-02-2022'
          image: 'assets/img/v3.4.jpg'
      'Release-01-2022':
          name: 'A new release of Fed-BioMed (v3.3)!'
          desc: 'A new release of Fed-BioMed is currently available: more robust, new ML frameworks, new functionalities, and much more!'
          link: '/news/Release-01-2022'
          image: 'assets/img/v3.3.jpg'
      'CHB':
          name: 'Fed-BioMed at Hospital Centre Henri Becquerel of Rouen'
          desc: 'A big thanks to the IT team of the Centre Henri Becquerel (CHB) of Rouen for the successful deployment of Fed-BioMed!'
          link: '/news/CHB'
          image: 'assets/img/CHB_team.jpg'
      'CAL':
          name: 'Fed-BioMed at Hospital Antoine Lacassagne of Nice'
          desc: 'We are proud to announce the successful deployment and testing of Fed-BioMed into the Hospital Antoine Lacassagne (CAL) of Nice!'
          link: '/pages/CAL'
          image: 'assets/img/Photo_CAL.jpg'
      'Roadmap':
          name: 'Fed-BioMed Roadmap'
          desc: 'The roadmap of Fed-BioMed is up to date'
          link: '/pages/roadmap'
          image: 'assets/img/Road-map_public.jpg'
      'MICCAI':
          name: 'Fed-BioMed @ MICCAI'
          desc: 'Fed-BioMed presented in the keynote session of the 2nd MICCAI Workshop on Distributed And Collaborative Learning'
          link: 'https://dcl-workshop.github.io/'
          image: 'assets/img/dcl.jpg'
      'hackAtech_n1':
          name: 'Fed-BioMed @ Inria hackAtech'
          desc: 'Fed-BioMed is an innovation technology presented at the next Inria hackAtech!'
          link: 'https://hackatechsophia.inria.fr/'
          image: 'assets/img/hackatech-2021.png'
      'workshop_n2':
          name: '3rd Federated Learning Workshop, Sorbonne University Paris'
          desc: 'Fed-BioMed presented at the 3rd Federated Learning Workshop organised by Owkin, Société Française de Statistique (SFdS), and Accenture Labs.'
          link: 'https://sites.google.com/view/federatedlearning-workshop'
          image: 'assets/img/workshop.jpg'
      'welcome_n3':
          name: 'Welcome to Sergen and Yannick!'
          desc: 'A warm welcome to Sergen Cansiz and Yannick Bouillard in the Fed-BioMed team!'
          link: '/news/welcome_08-2021'
          image: 'assets/img/welcome.jpg'

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
      lang: en
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      custom_templates: docs/.templates
      default_handler: python
      handlers:
        python:
          paths: fedbiomed
          import:
            - https://requests.readthedocs.io/en/master/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://scikit-learn.org/stable/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
          options:
            filters:
              - "!^__"
              - "!^_"
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_source: yes
            show_submodules: false
            show_if_no_docstring: true
            separate_signature: true
            separate_signature_for_function: false
            disable_private: true
            show_category_heading: true
            show_root_toc_entry: no
            show_root_full_path: true
  - minify:
      minify_html: true

  - redirects:
      redirect_maps:
        'getting-started/getting-started.md': 'getting-started/basic-example.md'
        'tutorials/installation/0-basic-software-installation.md': 'getting-started/installation.md'
        # 'old/file.md': 'new/file.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascript/lunr.js
  - assets/javascript/theme.js

extra_css:
  - assets/css/style.css
