version: "3.7"

services:
  #
  # restful http server component
  restful:
    container_name: fedbiomed-dev-restful
    hostname: fedbiomed-dev-restful
    build:
      context: ./restful/build_files
      args:
        - CONTAINER_UID
        - CONTAINER_GID
        - CONTAINER_USER
        - CONTAINER_GROUP
    image: fedbiomed/dev-restful
    #user: "${CONTAINER_UID:-root}:${CONTAINER_GID:-root}"
    environment:
      - PRODUCTION=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@nowhere.foo
      - DJANGO_SUPERUSER_PASSWORD=admin
    ports:
      - "8844:8000"
    volumes:
      - ./restful/run_mounts/app:/app # django application
  #
  # mosquitto server component
  mqtt:
    container_name: fedbiomed-dev-mqtt
    hostname: fedbiomed-dev-mqtt
    image: eclipse-mosquitto
    # enable mqtt without authentication
    entrypoint: [ "/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf" ]

    ports:
      - "1883:1883"
      - "9001:9001"
