version: '3'

services:
  api:
    container_name: fedbiomed-network
    build: .
    command: sh -c "gunicorn -w 4 -b 0.0.0.0:8000 --log-level debug fedbiomed.wsgi"
    user: "${CONTAINER_UID:-root}:${CONTAINER_GID:-root}"
    environment:
      - FORCE_SCRIPT_NAME
      - PRODUCTION=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=santiago-smith.silva-rincon@inria.fr
      - DJANGO_SUPERUSER_PASSWORD=admin123
    volumes:
      - .:/app
    ports:
      - "8844:8000"
  mosquitto:
    container_name: mosquitto
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
